[project]
name = "pool-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam Logan", email = "adamlogan42@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "blinker>=1.9.0",
    "boto3>=1.43.1",
    "faker>=40.15.0",
    "flask>=3.1.3",
    "flask-swagger-ui>=5.32.6",
    "mongoengine>=0.29.3",
    "slack-bolt>=1.28.0",
]

[project.scripts]
pool-tracker = "pool_tracker:main"
pool-tracker-server = "pool_tracker.flask_app:launch_server"
pool-tacker-slack-bot = "pool_tracker.slack_app:start_app"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[tool.pyright]
reportAttributeAccessIssue = "none"
